// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfyajordhbpskmxvurtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeWFqb3JkaGJwc2tteHZ1cnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjcwMDcsImV4cCI6MjA2MTAwMzAwN30.53VTkBjhEfm0Gsk0vUpXv1RD1x70visXTznBS5uvSzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);